application: gae-restx-poc
version: 1
runtime: java
api_version: 1
threadsafe: true

handlers:
- url: /api/@/*
  login: admin
  servlet: restx.servlet.RestxMainRouterServlet
  name: adminRouter

- url: /api/*
  servlet: restx.servlet.RestxMainRouterServlet
  name: mainRouter

